name: CI

on: [push, pull_request]

jobs:
  trial:
    if: false # Skip these for now
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9']
        toxenv: ['py,combine']
        include:
          - python-version: '3.9'
            toxenv: 'py-noextras,combine'

    steps:
    - uses: actions/checkout@v2

    - name: Install required Debian packages
      run: sudo apt-get -qq install xmlsec1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Tox
      run: python -m pip install tox

    - name: Test with tox
      run: tox
      env:
        TRIAL_FLAGS: "--jobs=2"
        TOXENV: ${{ matrix.toxenv }}

  trial-olddeps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test with old deps
      uses: docker://ubuntu:xenial  # For old python and sqlite
      with:
        workdir: /github/workspace
        entrypoint: .buildkite/scripts/test_old_deps.sh
      env:
        TRIAL_FLAGS: "--jobs=2"
